-- Baseline DDL (reliability/audit item 19).
--
-- Generated by:
--   npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script
-- from prisma/schema.prisma as of 2026-09-22, before any of that day's schema
-- hardening changes were applied to the schema file. It rebuilds an EMPTY
-- database to the exact shape the app's Prisma Client expects as of that date
-- (every table, column, default, index, unique and foreign-key constraint the
-- schema declares).
--
-- This file is NOT to be applied to the existing production database. It is
-- history/documentation only: a from-scratch snapshot for standing up a new
-- database (e.g. a fresh dev/staging copy), not a migration to run against
-- Supabase. Applying it to the live database would fail outright (every
-- CREATE TABLE already exists there) or, if hand-adapted and forced through,
-- would not match production's actual shape - see the next paragraph.
--
-- The live production database additionally still carries deprecated columns
-- that are NOT in prisma/schema.prisma and so do NOT appear below:
--   LineItem.leadTimeDays
--   PurchaseOrder.trackingUrl
--   PurchaseOrder.trackingCarrier
--   PurchaseOrder.expectedDelivery
--   PurchaseOrder.trucker
--   PurchaseOrder.pickupAddress
--   PurchaseOrder.scheduledDeliveryDate
--   PurchaseOrder.shipCost
--   PurchaseOrder.chargedToCustomer
--   PurchaseOrder.deliveryContactPhone
--   PurchaseOrder.deliveryStatus
-- These were backfilled into Delivery by 20260903_sales_orders_delivery.sql
-- and Prisma no longer maps them (see the LineItem/PurchaseOrder model
-- comments in prisma/schema.prisma), but the columns themselves were never
-- dropped from Postgres. See prisma/sql/OPTIONAL_drop_deprecated_columns.sql
-- for the optional, destructive script that would finally drop them.
--
-- The later, dated files in this folder (20260903_..., 20260907_...,
-- 20260908_..., 20260917_..., 20260922_schema_hardening.sql, ...) are what
-- actually apply on top of production's real, already-evolved shape. Together
-- with this file they document the full history of the schema, but only the
-- dated files are ever meant to be run against Supabase.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'sales',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "passwordHash" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Company" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'customer',
    "vertical" TEXT,
    "priorityClient" BOOLEAN NOT NULL DEFAULT false,
    "requiresDeposit" BOOLEAN NOT NULL DEFAULT true,
    "depositPercent" INTEGER NOT NULL DEFAULT 30,
    "phone" TEXT,
    "phoneExt" TEXT,
    "cellPhone" TEXT,
    "email" TEXT,
    "deliveryAddress" TEXT,
    "billingAddress" TEXT,
    "locationName" TEXT,
    "zip" TEXT,
    "website" TEXT,
    "notes" TEXT,
    "mondayId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Company_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Location" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "deliveryNotes" TEXT,
    "contactName" TEXT,
    "contactPhone" TEXT,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Location_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SupplierProfile" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "accountNumber" TEXT,
    "defaultLeadTimeDays" INTEGER,
    "repNotes" TEXT,
    "preferred" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "SupplierProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Contact" (
    "id" TEXT NOT NULL,
    "companyId" TEXT,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT,
    "title" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "phoneExt" TEXT,
    "cellPhone" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "notes" TEXT,
    "mondayId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Contact_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Opportunity" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "companyId" TEXT,
    "primaryContactId" TEXT,
    "salespersonId" TEXT,
    "stage" TEXT NOT NULL DEFAULT 'new',
    "orderType" TEXT NOT NULL DEFAULT 'order',
    "needsPricing" BOOLEAN NOT NULL DEFAULT true,
    "value" DOUBLE PRECISION,
    "neededByDate" TIMESTAMP(3),
    "estDueDate" TIMESTAMP(3),
    "nextFollowUp" TIMESTAMP(3),
    "lostReason" TEXT,
    "facilityType" TEXT,
    "menu" TEXT,
    "roomDimensions" TEXT,
    "wallMeasurements" TEXT,
    "plumbingElectricalNotes" TEXT,
    "budget" DOUBLE PRECISION,
    "clientVisionNotes" TEXT,
    "deliveryType" TEXT,
    "openingSize" TEXT,
    "installationNeeded" BOOLEAN NOT NULL DEFAULT false,
    "designStatus" TEXT NOT NULL DEFAULT 'none',
    "locationId" TEXT,
    "locationName" TEXT,
    "deliveryAddress" TEXT,
    "submittedVia" TEXT NOT NULL DEFAULT 'manual',
    "notes" TEXT,
    "mondayId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Opportunity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LineItem" (
    "id" TEXT NOT NULL,
    "opportunityId" TEXT,
    "orderId" TEXT,
    "purchaseOrderId" TEXT,
    "deliveryId" TEXT,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "moreDetails" TEXT,
    "imageUrl" TEXT,
    "qty" INTEGER NOT NULL DEFAULT 1,
    "itemKind" TEXT NOT NULL DEFAULT 'sourced',
    "brand" TEXT,
    "sku" TEXT,
    "supplierId" TEXT,
    "unitCost" DOUBLE PRECISION,
    "unitPrice" DOUBLE PRECISION,
    "leadTimeDate" TIMESTAMP(3),
    "rfqStatus" TEXT NOT NULL DEFAULT 'needs_pricing',
    "stockStatus" TEXT NOT NULL DEFAULT 'in_stock',
    "deliveryStatus" TEXT NOT NULL DEFAULT 'pending',
    "backorderExpected" TIMESTAMP(3),
    "dateOrdered" TIMESTAMP(3),
    "dateArrivedHss" TIMESTAMP(3),
    "dateArrivedClient" TIMESTAMP(3),
    "trackingUrl" TEXT,
    "assigneeId" TEXT,
    "nextFollowUp" TIMESTAMP(3),
    "followedUp" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "mondayId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LineItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Order" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "opportunityId" TEXT,
    "companyId" TEXT,
    "contactId" TEXT,
    "ownerId" TEXT,
    "orderType" TEXT NOT NULL DEFAULT 'order',
    "status" TEXT NOT NULL DEFAULT 'new',
    "clientPoNumber" TEXT,
    "jobId" TEXT,
    "quickbooksInvoiceNo" TEXT,
    "orderValue" DOUBLE PRECISION,
    "depositRequired" DOUBLE PRECISION,
    "locationId" TEXT,
    "deliveryAddress" TEXT,
    "neededByDate" TIMESTAMP(3),
    "nextFollowUp" TIMESTAMP(3),
    "paymentTerms" TEXT,
    "termsNotes" TEXT,
    "quoteStatus" TEXT NOT NULL DEFAULT 'not_needed',
    "quoteUrl" TEXT,
    "quoteSentAt" TIMESTAMP(3),
    "notes" TEXT,
    "mondayId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PurchaseOrder" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "supplierId" TEXT,
    "poNumber" TEXT,
    "autoQuotesPoNumber" TEXT,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "shipTo" TEXT NOT NULL DEFAULT 'hss',
    "sentDate" TIMESTAMP(3),
    "ackDate" TIMESTAMP(3),
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PurchaseOrder_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Delivery" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "purchaseOrderId" TEXT,
    "mode" TEXT NOT NULL DEFAULT 'manufacturer_to_hss_to_customer',
    "status" TEXT NOT NULL DEFAULT 'pending',
    "trackingCarrier" TEXT,
    "trackingUrl" TEXT,
    "expectedDelivery" TIMESTAMP(3),
    "trucker" TEXT,
    "pickupAddress" TEXT,
    "scheduledDeliveryDate" TIMESTAMP(3),
    "shipCost" DOUBLE PRECISION,
    "chargedToCustomer" BOOLEAN NOT NULL DEFAULT false,
    "deliveryContactPhone" TEXT,
    "deliveredAt" TIMESTAMP(3),
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Delivery_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Payment" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "quickbooksRef" TEXT,
    "date" TIMESTAMP(3),
    "source" TEXT NOT NULL DEFAULT 'manual',
    "dueNote" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Payment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Task" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "notes" TEXT,
    "assigneeId" TEXT,
    "dueDate" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'not_started',
    "priority" TEXT NOT NULL DEFAULT 'medium',
    "type" TEXT NOT NULL DEFAULT 'internal',
    "estimatedHours" DOUBLE PRECISION,
    "linkedType" TEXT,
    "linkedId" TEXT,
    "parentTaskId" TEXT,
    "mondayId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TaskComment" (
    "id" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "authorId" TEXT,
    "authorName" TEXT,
    "body" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TaskComment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "IntakeSubmission" (
    "id" TEXT NOT NULL,
    "payload" TEXT NOT NULL,
    "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processed" BOOLEAN NOT NULL DEFAULT false,
    "resultType" TEXT,
    "resultId" TEXT,
    "mondayId" TEXT,

    CONSTRAINT "IntakeSubmission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Document" (
    "id" TEXT NOT NULL,
    "linkedType" TEXT NOT NULL,
    "linkedId" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'other',
    "fileUrl" TEXT NOT NULL,
    "fileName" TEXT,
    "source" TEXT NOT NULL DEFAULT 'link',
    "mimeType" TEXT,
    "sizeBytes" INTEGER,
    "storagePath" TEXT,
    "uploadedBy" TEXT,
    "note" TEXT,
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Document_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ActivityLog" (
    "id" TEXT NOT NULL,
    "userName" TEXT,
    "linkedType" TEXT NOT NULL,
    "linkedId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "detail" TEXT,
    "previousValue" TEXT,
    "newValue" TEXT,
    "sourceScreen" TEXT,
    "at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ActivityLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FieldRequirement" (
    "id" TEXT NOT NULL,
    "entity" TEXT NOT NULL,
    "field" TEXT NOT NULL,
    "required" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "FieldRequirement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ServiceIssue" (
    "id" TEXT NOT NULL,
    "companyId" TEXT,
    "locationId" TEXT,
    "orderId" TEXT,
    "lineItemId" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'open',
    "priority" TEXT NOT NULL DEFAULT 'medium',
    "assigneeId" TEXT,
    "reportedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolvedAt" TIMESTAMP(3),
    "resolution" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ServiceIssue_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RolePermission" (
    "id" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "permission" TEXT NOT NULL,
    "allowed" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "RolePermission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AppSetting" (
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AppSetting_pkey" PRIMARY KEY ("key")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Company_mondayId_key" ON "Company"("mondayId");

-- CreateIndex
CREATE INDEX "Location_companyId_idx" ON "Location"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "SupplierProfile_companyId_key" ON "SupplierProfile"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "Contact_mondayId_key" ON "Contact"("mondayId");

-- CreateIndex
CREATE INDEX "Contact_companyId_idx" ON "Contact"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "Opportunity_mondayId_key" ON "Opportunity"("mondayId");

-- CreateIndex
CREATE INDEX "Opportunity_stage_idx" ON "Opportunity"("stage");

-- CreateIndex
CREATE INDEX "Opportunity_companyId_idx" ON "Opportunity"("companyId");

-- CreateIndex
CREATE INDEX "Opportunity_salespersonId_idx" ON "Opportunity"("salespersonId");

-- CreateIndex
CREATE INDEX "Opportunity_nextFollowUp_idx" ON "Opportunity"("nextFollowUp");

-- CreateIndex
CREATE INDEX "Opportunity_locationId_idx" ON "Opportunity"("locationId");

-- CreateIndex
CREATE UNIQUE INDEX "LineItem_mondayId_key" ON "LineItem"("mondayId");

-- CreateIndex
CREATE INDEX "LineItem_rfqStatus_idx" ON "LineItem"("rfqStatus");

-- CreateIndex
CREATE INDEX "LineItem_stockStatus_idx" ON "LineItem"("stockStatus");

-- CreateIndex
CREATE INDEX "LineItem_deliveryStatus_idx" ON "LineItem"("deliveryStatus");

-- CreateIndex
CREATE INDEX "LineItem_opportunityId_idx" ON "LineItem"("opportunityId");

-- CreateIndex
CREATE INDEX "LineItem_orderId_idx" ON "LineItem"("orderId");

-- CreateIndex
CREATE INDEX "LineItem_purchaseOrderId_idx" ON "LineItem"("purchaseOrderId");

-- CreateIndex
CREATE INDEX "LineItem_deliveryId_idx" ON "LineItem"("deliveryId");

-- CreateIndex
CREATE INDEX "LineItem_supplierId_idx" ON "LineItem"("supplierId");

-- CreateIndex
CREATE INDEX "LineItem_nextFollowUp_idx" ON "LineItem"("nextFollowUp");

-- CreateIndex
CREATE UNIQUE INDEX "Order_mondayId_key" ON "Order"("mondayId");

-- CreateIndex
CREATE INDEX "Order_status_idx" ON "Order"("status");

-- CreateIndex
CREATE INDEX "Order_companyId_idx" ON "Order"("companyId");

-- CreateIndex
CREATE INDEX "Order_opportunityId_idx" ON "Order"("opportunityId");

-- CreateIndex
CREATE INDEX "Order_locationId_idx" ON "Order"("locationId");

-- CreateIndex
CREATE INDEX "Order_neededByDate_idx" ON "Order"("neededByDate");

-- CreateIndex
CREATE INDEX "Order_nextFollowUp_idx" ON "Order"("nextFollowUp");

-- CreateIndex
CREATE INDEX "PurchaseOrder_orderId_idx" ON "PurchaseOrder"("orderId");

-- CreateIndex
CREATE INDEX "PurchaseOrder_supplierId_idx" ON "PurchaseOrder"("supplierId");

-- CreateIndex
CREATE INDEX "PurchaseOrder_status_idx" ON "PurchaseOrder"("status");

-- CreateIndex
CREATE UNIQUE INDEX "PurchaseOrder_orderId_poNumber_key" ON "PurchaseOrder"("orderId", "poNumber");

-- CreateIndex
CREATE INDEX "Delivery_orderId_idx" ON "Delivery"("orderId");

-- CreateIndex
CREATE INDEX "Delivery_purchaseOrderId_idx" ON "Delivery"("purchaseOrderId");

-- CreateIndex
CREATE INDEX "Delivery_status_idx" ON "Delivery"("status");

-- CreateIndex
CREATE INDEX "Payment_orderId_idx" ON "Payment"("orderId");

-- CreateIndex
CREATE UNIQUE INDEX "Task_mondayId_key" ON "Task"("mondayId");

-- CreateIndex
CREATE INDEX "Task_status_idx" ON "Task"("status");

-- CreateIndex
CREATE INDEX "Task_assigneeId_idx" ON "Task"("assigneeId");

-- CreateIndex
CREATE INDEX "Task_parentTaskId_idx" ON "Task"("parentTaskId");

-- CreateIndex
CREATE INDEX "Task_linkedType_linkedId_idx" ON "Task"("linkedType", "linkedId");

-- CreateIndex
CREATE INDEX "TaskComment_taskId_idx" ON "TaskComment"("taskId");

-- CreateIndex
CREATE UNIQUE INDEX "IntakeSubmission_mondayId_key" ON "IntakeSubmission"("mondayId");

-- CreateIndex
CREATE INDEX "Document_linkedType_linkedId_idx" ON "Document"("linkedType", "linkedId");

-- CreateIndex
CREATE INDEX "ActivityLog_linkedType_linkedId_idx" ON "ActivityLog"("linkedType", "linkedId");

-- CreateIndex
CREATE INDEX "ActivityLog_userName_idx" ON "ActivityLog"("userName");

-- CreateIndex
CREATE INDEX "ActivityLog_action_idx" ON "ActivityLog"("action");

-- CreateIndex
CREATE INDEX "ActivityLog_at_idx" ON "ActivityLog"("at");

-- CreateIndex
CREATE UNIQUE INDEX "FieldRequirement_entity_field_key" ON "FieldRequirement"("entity", "field");

-- CreateIndex
CREATE INDEX "ServiceIssue_status_idx" ON "ServiceIssue"("status");

-- CreateIndex
CREATE INDEX "ServiceIssue_assigneeId_idx" ON "ServiceIssue"("assigneeId");

-- CreateIndex
CREATE INDEX "ServiceIssue_orderId_idx" ON "ServiceIssue"("orderId");

-- CreateIndex
CREATE INDEX "ServiceIssue_companyId_idx" ON "ServiceIssue"("companyId");

-- CreateIndex
CREATE INDEX "ServiceIssue_locationId_idx" ON "ServiceIssue"("locationId");

-- CreateIndex
CREATE INDEX "ServiceIssue_lineItemId_idx" ON "ServiceIssue"("lineItemId");

-- CreateIndex
CREATE UNIQUE INDEX "RolePermission_role_permission_key" ON "RolePermission"("role", "permission");

-- AddForeignKey
ALTER TABLE "Location" ADD CONSTRAINT "Location_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SupplierProfile" ADD CONSTRAINT "SupplierProfile_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Contact" ADD CONSTRAINT "Contact_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Opportunity" ADD CONSTRAINT "Opportunity_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Opportunity" ADD CONSTRAINT "Opportunity_primaryContactId_fkey" FOREIGN KEY ("primaryContactId") REFERENCES "Contact"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Opportunity" ADD CONSTRAINT "Opportunity_salespersonId_fkey" FOREIGN KEY ("salespersonId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Opportunity" ADD CONSTRAINT "Opportunity_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LineItem" ADD CONSTRAINT "LineItem_opportunityId_fkey" FOREIGN KEY ("opportunityId") REFERENCES "Opportunity"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LineItem" ADD CONSTRAINT "LineItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LineItem" ADD CONSTRAINT "LineItem_purchaseOrderId_fkey" FOREIGN KEY ("purchaseOrderId") REFERENCES "PurchaseOrder"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LineItem" ADD CONSTRAINT "LineItem_deliveryId_fkey" FOREIGN KEY ("deliveryId") REFERENCES "Delivery"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LineItem" ADD CONSTRAINT "LineItem_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LineItem" ADD CONSTRAINT "LineItem_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_opportunityId_fkey" FOREIGN KEY ("opportunityId") REFERENCES "Opportunity"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "Contact"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PurchaseOrder" ADD CONSTRAINT "PurchaseOrder_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PurchaseOrder" ADD CONSTRAINT "PurchaseOrder_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Delivery" ADD CONSTRAINT "Delivery_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Delivery" ADD CONSTRAINT "Delivery_purchaseOrderId_fkey" FOREIGN KEY ("purchaseOrderId") REFERENCES "PurchaseOrder"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_parentTaskId_fkey" FOREIGN KEY ("parentTaskId") REFERENCES "Task"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaskComment" ADD CONSTRAINT "TaskComment_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TaskComment" ADD CONSTRAINT "TaskComment_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceIssue" ADD CONSTRAINT "ServiceIssue_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceIssue" ADD CONSTRAINT "ServiceIssue_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceIssue" ADD CONSTRAINT "ServiceIssue_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceIssue" ADD CONSTRAINT "ServiceIssue_lineItemId_fkey" FOREIGN KEY ("lineItemId") REFERENCES "LineItem"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceIssue" ADD CONSTRAINT "ServiceIssue_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

